# Generated by Django 3.1 on 2022-05-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='')),
                ('name', models.CharField(max_length=50, verbose_name='Аты')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилиясы')),
                ('email', models.EmailField(max_length=50, verbose_name='Электрондық почта')),
                ('city', models.CharField(max_length=50, verbose_name='Қала')),
                ('mobile_number', models.IntegerField(max_length=11, verbose_name='Ьобилдік нөмері')),
            ],
        ),
    ]
