# Generated by Django 3.1 on 2022-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='anonymous', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.IntegerField(verbose_name='Ьобилдік нөмері'),
        ),
    ]
